### ISSUE TITLE
你好，我来自剑三贴吧

### ISSUE THREAD

**Issue by archichen** [swordsbird/JX3Price#1]
你好，我来自剑三贴吧，就是那个想吃烧烤。很高兴能看到一个和剑三有关的开源项目。也想参与一下。

我的技术栈：

后端：Java + SpringCloud全家桶。

前端：ReactJS全家桶

数据库：MongoDB，Redis，MongoDB

大数据：Hadoop，Spark，Flink，Hive

其他：Kafka，Cassandra，Jenkins，Ansible，Python

看了下项目使用的技术，和我不怎么match...但是还是比较开心的哈哈哈（正经的JX3开源项目太少了，除了插件普通玩家没法涉足，其他的都是年久失修）。

我之前想过做类似的，但是不会ML，所以非常费力就弃了（之前想的是贴吧信息分词，然后wordcount后做匹配......）。我想过实现一个剑三物品的成交价格历史走势，方便PVG自己解决金币来源，但是剑三的基址太难得到了（主要我菜，没这方面技术积累），也弃了。

hhh，反正，很高兴知道这个项目，如果有需要我的地方尽管开口。后面我有时间也会自己看看能做点什么。

**Comment by swordsbird** [comment]
感谢支持！开始做本项目前，我也没有过tensorflow的使用经验，算是有一点机器学习的基础吧。剑三信息分词的难点是外观和其他游戏道具的名称难以识别，而现有的NLP工具已经很完善了，因此这里我用了手动+规则的方式生成了外观及其同义词库，可以参见nlppack文件夹，希望能给你一点贴吧分词上的启发。

不必谦虚，你的技术栈也很丰富了，即使可能和这个项目不是特别match，也欢迎提出各种建议，或者从中找到自己可以用到的，谢谢~

**Comment by swordsbird** [comment]
这里也可以说一下本项目未来可能会做的事情：

1. 账号外观选择偏好的群体刻画。大概就是做个聚类找找pattern。
2. 账号数据的数据增广。通过半自动合成账号数据的方式，修正账号在门派、价格区间、体型上的分布差异，这个是为了提高准确率。
3. 改善用户界面，当前对手机的适配考虑的比较多，后面要把桌面端的体验也改善一下。
